apiVersion: apps/v1
kind: Deployment
metadata:
  name: sm-user
  namespace: subsmanager
  labels:
    app: sm-user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sm-user
  template:
    metadata:
      labels:
        app: sm-user
    spec:
      containers:
        - name: sm-user
          image: devwikirepo/sm-user:1.0.1
          envFrom:
            - configMapRef:
                name: postgres-config
            - secretRef:
                name: postgres-secret
            - secretRef:
                name: jwt-secret
          env:
            - name: DB_NAME
              value: user_service
---
apiVersion: v1
kind: Service
metadata:
  name: sm-user
  namespace: subsmanager
  labels:
    app: sm-user
spec:
  selector:
    app: sm-user
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP
