apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sm-db-pvc
  namespace: subsmanager
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi