apiVersion: v1
kind: PersistentVolume
metadata:
  name: sm-db-pv
  namespace: subsmanager
spec:
  storageClassName: ""
  capacity:
    storage: 512Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/sm-db
