@baseUrl = http://localhost:5005
@authToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTczODA2Mzg0NSwianRpIjoiMDVhYTI5N2EtMjY4Ni00N2UzLWFjYzYtZGUzNGMzN2M2YTM4IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6IjE2IiwibmJmIjoxNzM4MDYzODQ1LCJjc3JmIjoiYmIzMjkzMjktYzk4MC00Nzk3LWEwNjctZjJlOWE4ZDYzOTY3IiwiZXhwIjoxNzM4MDY3NDQ1LCJlbWFpbCI6InRlc3RAdGVzdC5jb20ifQ.dp5wCwwPDTHpr6OOEuOQYwU4kL0qIAn7zeP_g1YHtBY

### Register
POST {{baseUrl}}/users/register
Content-Type: application/json

{
 "email": "test@test.com",
 "username": "testuser",
 "password": "testpass123",
 "full_name": "Test User"
}

### Login Request
POST {{baseUrl}}/users/login
Content-Type: application/json

{
   "email": "test@test.com",
   "password": "testpass123"
}

### Use the extracted accessToken
GET {{baseUrl}}/users/me
Authorization: Bearer {{authToken}}

### Get Specific User Information
GET {{baseUrl}}/users/3
Authorization: Bearer {{authToken}}

### Update User Information
PUT {{baseUrl}}/users/16
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
 "email": "updated@test.com",
 "username": "updateduser",
 "full_name": "Updated User"
}

### Delete User
DELETE {{baseUrl}}/users/3
Authorization: Bearer {{authToken}}