apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sm-db-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: sm-front
    http:
      paths:
      - path: /front
        pathType: Prefix
        backend:
          service:
            name: sm-front
            port:
              number: 80